language: ruby
cache: bundler
rvm:
  - 2.5.4
before_install:
  - travis_retry sudo apt-get update
install:
  - sudo bash -c "curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/ubuntu.sh | bash"
  - nvm use mn-node
  - export NODE_PATH=$(npm root -g)
before_script:
  - gem install bundler
  - bundle
  - make update-init update-modules
script:
  - make all
before_deploy:
  - pip install --user awscli
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $S3_BUCKET_NAME
    region: $AWS_REGION
    skip_cleanup: true
    local_dir: _site
    on:
      branch: master
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $S3_STAGING_BUCKET_NAME
    region: $AWS_REGION
    skip_cleanup: true
    local_dir: _site
    on:
      branch: staging
after_deploy:
  - aws configure set preview.cloudfront true
  - test $TRAVIS_BRANCH = "master" && aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
  - test $TRAVIS_BRANCH = "staging" && aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_STAGING_DISTRIBUTION_ID --paths "/*"
