language: ruby
dist: xenial
cache: bundler
rvm:
  - 2.5
addons:
  apt:
    update: true
    packages:
      - curl
      - git
      - make
  snaps:
    - jq
    - yq
    - name: aws-cli
      confinement: classic # or devmode
    - name: node
      confinement: classic # or devmode
      channel: 10/stable
before_install:
  - travis_retry sudo apt-get update
install:
  - sudo bash -c "curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/ubuntu.sh | bash"
  - nvm use mn-node
  - export NODE_PATH=$(npm root -g)
  - travis_retry gem install bundler
before_script:
  - bundle
  - make update-init update-modules
script:
  - make _site
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $S3_BUCKET_NAME
    region: $AWS_REGION
    skip_cleanup: true
    local_dir: _site
    on:
      branch: master
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $S3_STAGING_BUCKET_NAME
    region: $AWS_REGION
    skip_cleanup: true
    local_dir: _site
    on:
      branch: staging
after_deploy:
  - aws configure set preview.cloudfront true
  - test $TRAVIS_BRANCH = "master" && aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
  - test $TRAVIS_BRANCH = "staging" && aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_STAGING_DISTRIBUTION_ID --paths "/*"
